version: '3.5'
services:
  db:
    image: postgres:11
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - db.env

  app:
    image: nextcloud:15.0.5
    restart: always
    volumes:
      - nextcloud:/var/www/html
    environment:
      - POSTGRES_HOST=db
    env_file:
      - db.env
    depends_on:
      - db
    networks:
      - server-net
    container_name: nextcloud

networks:
  server-net:
    external: true
    name: server-net

volumes:
  db:
  nextcloud: