version: '3.5'
services:
  db:
    image: postgres:11
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
  app:
    image: nextcloud:16.0.1
    restart: always
    volumes:
      - nextcloud:/var/www/html
    env_file:
      - nc.env
    depends_on:
      - db
  web:
    build: ./caddy
    restart: always
    volumes:
      - caddy:/root/.caddy/
    ports:
      - "80:80"
      - "443:443"

volumes:
  db:
  nextcloud:
  caddy: