version: '3.5'
services:
  db:
    image: postgres:11
    restart: always
    volumes:
      - db:/var/lib/postgresql/data

  app:
    image: nextcloud:16.0.1
    restart: always
    volumes:
      - nextcloud:/var/www/html
    env_file:
      - db.env
    depends_on:
      - db
    ports:
      - 80:80

volumes:
  db:
  nextcloud: